"use client";

import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import { profileContent } from "./profile-content";

type Profile = { slug:string; name:string; company:string; role:string; initials:string; color:string; lens:string; thesis:string; intro:string; agents:string[]; human:string; caseTitle:string; caseText:string; questions:string[]; provocation:string; mermaid:string };
const P=(slug:string,name:string,company:string,role:string,initials:string,color:string,lens:string,thesis:string,intro:string,agents:string[],human:string,caseTitle:string,caseText:string,questions:string[],provocation:string,mermaid:string):Profile=>({slug,name,company,role,initials,color,lens,thesis,intro,agents,human,caseTitle,caseText,questions,provocation,mermaid});

const profiles:Profile[]=[
P("tom-leite","Tom Leite","Grupo Trigo","CEO · rede · franchising","TL","#ff6b35","Sistema operacional da rede","E se o Grupo Trigo tivesse um sistema de gestão capaz de coordenar especialistas digitais da mesma maneira que a holding coordena marcas, fábrica, franqueados e operações?","O perfil público atual o posiciona na presidência do Grupo Trigo e da ABF. Para ele, a experiência evita abrir com arquitetura tecnológica.",["Dados & margem","Supply & estoque","Franquia & suporte"],"Define prioridades, arbitra exceções e decide o que deve ser padrão na rede.","Grupo Trigo · 2026","Agentes já apoiam capacitação de franqueados, dúvidas financeiras e suporte. O Tommy disponibiliza BI em linguagem natural.",["Onde a IA deveria gerar valor primeiro: consumidor, franqueado, supply ou pessoas?","Ela deve informar, recomendar ou executar ações pré-aprovadas?","Onde preservar autonomia local e onde padronizar a rede?","Qual resultado deve orientar o sistema: margem, vendas, estoque, SLA ou experiência?"],"Que decisões hoje ficam no centro porque a informação está fragmentada, mas poderiam migrar para a ponta?","flowchart TD\n A[Objetivo do presidente] --> O[Orquestrador]\n O --> D[Dados e margem]\n O --> S[Supply e estoque]\n O --> F[Franquia e suporte]\n D --> R[Recomendação]\n S --> R\n F --> R\n R --> H{Decisão humana}\n H --> K[Resultado por loja]"),
P("luiz-marcelo","Luiz Marcelo","Grupo Trigo","CDO · CTO · CIO","LM","#6c63ff","Control plane corporativo","Qual deve ser o control plane que conecta os agentes que o negócio começa a espalhar por dados, suporte, franquias, software, CRM, supply e operação?","O desafio é conectar agentes em dados, suporte, franquias, software, CRM, supply e operação — sem perder estado, identidade, política, custo e observabilidade.",["BI Agent","Support Agent","Supply Agent"],"Desenha a plataforma, define limites de autonomia e supervisiona qualidade, custo e risco.","Grupo Trigo · arquitetura 2026","O contexto real da companhia torna concreta a passagem de iniciativas isoladas para uma plataforma comum de agentes.",["Quais três domínios deveriam compartilhar contexto hoje?","Onde o fluxo deve ser determinístico e onde o agente pode planejar?","Qual gargalo preocupa mais: integração, qualidade, latência, custo, segurança ou observabilidade?","Qual ação pode ser autônoma e qual exige approval gate?"],"Qual passa a ser o produto da tecnologia: cada agente ou a plataforma que governa todos eles?","flowchart TD\n U[Usuário, evento ou KPI] --> R[Router e planner]\n R --> B[BI Agent]\n R --> S[Support Agent]\n R --> P[Supply Agent]\n B --> C[Estado, identidade e policy]\n S --> C\n P --> C\n C --> G{Approval gate}\n G --> X[Ação observável]"),
P("jose-henrique","José Henrique Moreira","BTG Pactual","Private Banking","JH","#159a8c","Advisor cockpit multiagente","Imagine que, antes de cada conversa com um cliente, um orquestrador monte e coordene uma equipe digital de research, portfolio analytics, documentação, suitability/compliance e client intelligence — e lhe entregue uma visão única, com fontes e exceções.","Antes de cada conversa, especialistas de research, portfólio, documentação, suitability e client intelligence trabalham juntos — sem substituir o julgamento do banker.",["Research","Portfolio analytics","Compliance & service"],"Interpreta o contexto, decide e sustenta a relação de confiança com o cliente.","Goldman Sachs + Anthropic · 2026","Agentes especializados foram anunciados para accounting, due diligence de clientes e onboarding.",["Onde existe maior perda de tempo antes e depois das reuniões?","O agente deve sintetizar, recomendar ou executar processos administrativos?","Que informação precisa vir acompanhada da fonte original?","Que decisão jamais deve chegar ao cliente sem sua validação?"],"Quanto mais análise um agente produz, o que passa a diferenciar um grande banker?","flowchart TD\n C[Cliente] --> B[Private banker]\n B --> O[Orquestrador]\n O --> R[Research]\n O --> P[Portfolio]\n O --> K[Compliance]\n R --> U[Brief único]\n P --> U\n K --> U\n U --> D{Decisão do banker}"),
P("joao-pinho","João Carlos Távora Pinho","Kapitalo","Asset management","JP","#d34c72","Federação de especialistas","Em vez de um superagente que tenta saber tudo, imagine um conjunto de especialistas trabalhando em paralelo.","Em vez de um superagente, especialistas trabalham em paralelo. O orquestrador sabe quem consultar, preserva o dissenso e agrega exposições.",["Macro","Empresas","Risco & execução"],"Avalia teses, lê o dissenso e assume a decisão de portfólio.","BCG Asset Management · 2026","A visão setorial descreve agentes em pesquisa, portfólio, trading, operações e reporting coordenados por uma camada comum.",["O orquestrador deve buscar consenso ou preservar teses divergentes?","Quais especialistas deveriam trabalhar em paralelo?","Qual contexto deve permanecer isolado entre agentes?","Onde análise termina e decisão começa?"],"Como preservar teses independentes sem criar um agente que transforme divergência em média?","flowchart TD\n P[PM ou CIO] --> O[Orquestrador]\n O --> M[Macro]\n O --> E[Empresas]\n O --> R[Risco]\n M --> D[Dissenso explícito]\n E --> D\n R --> D\n D --> V[Portfolio view]\n V --> H{Decisão humana}"),
P("flavio-clemente","Flávio Clemente","Heuris","Family Office · investimentos","FC","#2674d9","Family Office Decision Room","Cenário proposto: uma Family Office Decision Room.","A arquitetura amplia a capacidade de decisão sem dissolver contexto familiar, propósito ou confidencialidade.",["Investment research","Risk exposure","Governance & impact"],"Conecta evidências ao mandato, ao contexto familiar e ao julgamento de longo prazo.","Family Offices · pesquisa 2026","A agenda brasileira aponta demanda crescente por curadoria, personalização e governança em patrimônio, sucessão e legado.",["Onde há maior escassez de atenção: research, portfólio, documentos, risco ou agenda familiar?","O sistema deve otimizar retorno, mandato ou capacidade de decisão?","Quais informações familiares precisam ficar isoladas?","Que recomendação sempre exige discussão humana?"],"Que decisões de patrimônio ganham com mais informação — e quais continuam dependendo de contexto familiar?","flowchart TD\n I[Intenção da família] --> O[Orquestrador]\n O --> V[Investimentos]\n O --> R[Risco]\n O --> G[Governança e impacto]\n V --> B[Decision book]\n R --> B\n G --> B\n B --> H{Família e time}"),
P("nadja-brandao","Nadja Brandão","Governança & Conselhos","Jurídico · ESG · board","NB","#8d5a3b","Governance layer","Quem governa os agentes que passam a governar partes do processo?","A pergunta central não é produtividade. É quem governa os agentes que passam a governar partes do processo.",["Legal","ESG","Finance & evidence"],"Desenha direitos de decisão, resolve conflitos e responde pela accountability.","Freshfields + Anthropic · 2026","Ferramentas para drafting, revisão contratual e due diligence mantêm a supervisão profissional no centro.",["O que mais aumenta confiança: fonte, explicação, auditoria ou aprovação?","Quais ações precisam ser sempre policy-driven?","O sistema deve bloquear, alertar ou escalar exceções?","Quem responde quando agentes ou políticas entram em conflito?"],"Qual será o equivalente da matriz de alçadas quando quem inicia uma ação é um agente?","flowchart TD\n B[Business request] --> O[Orchestrator]\n O --> L[Legal]\n O --> E[ESG]\n O --> F[Finance]\n L --> G[Governance layer]\n E --> G\n F --> G\n G --> H{Board ou executivo}"),
P("luis-chicani","Luís Alexandre Chicani","BenCorp · ClubSaúde","Benefícios & saúde corporativa","LC","#25a56a","Navegação de benefícios","Cenário proposto: uma orquestração da jornada de benefícios.","O valor está em conectar identidade, elegibilidade, regras, atendimento e encaminhamento — separando automação administrativa de decisões sensíveis.",["Eligibility & policy","Network navigation","Benefit support"],"Aconselha, negocia e cuida das exceções que pedem contexto e responsabilidade.","Oracle · arquiteturas 2026","Aplicações agentic passam a coordenar dados e processos de negócio em torno do resultado solicitado pelo usuário.",["Qual jornada simplificar primeiro: colaborador, RH, operadora ou time interno?","Qual informação precisa acompanhar o usuário entre sistemas?","Que dado não deve ser compartilhado entre agentes por padrão?","Onde o humano gera mais valor: aconselhamento, exceção, negociação ou cuidado?"],"Que partes da jornada devem compartilhar contexto e quais precisam de separação deliberada?","flowchart TD\n C[Colaborador ou RH] --> O[Benefit orchestrator]\n O --> E[Elegibilidade]\n O --> N[Rede]\n O --> S[Suporte]\n E --> X[Contexto e encaminhamento]\n N --> X\n S --> X\n X --> H{Especialista humano}"),
P("mauricio-magalhaes","Maurício Magalhães","Mundo Real","Estratégia & marketing","MM","#e89b2d","Sinais → estratégia → execução","A orquestração pode assumir a forma da metodologia da Mundo Real.","A experiência assume a lógica da Mundo Real: observar, reenquadrar o problema, clarear o caminho e reprogramar a trajetória.",["Consumidor","Marca","Mercado"],"Faz o reframing, escolhe a tese e protege o repertório distintivo da marca.","T-Mobile + Gradial · 2026","A companhia reportou redução de 80%–90% no tempo de execução de campanhas com uma camada agentic.",["Onde a IA participa mais: leitura, reframing, cenários ou execução?","Que parte do processo exige repertório humano distintivo?","Um agente converge ou vários defendem leituras concorrentes?","Que elementos de marca devem permanecer como restrições fixas?"],"Quando produzir alternativas fica barato, a vantagem migra da criação para a escolha?","flowchart TD\n S[Sinais do mundo real] --> O[Observação]\n O --> R[Reframe do problema]\n R --> C[Consumidor]\n R --> M[Marca]\n R --> K[Mercado]\n C --> X[Cenários]\n M --> X\n K --> X\n X --> E[Estratégia e execução]"),
P("patricia-coimbra","Patrícia Coimbra","Porto","Gente · cultura · ESG","PC","#7358c7","Força de trabalho híbrida","Quando agentes passam a fazer trabalho, quem desenha a força de trabalho?","Quando agentes passam a fazer trabalho, o foco muda de tecnologia para work design: tarefas, papéis, skills, cultura, incentivos e accountability.",["Human-led","AI-assisted","Agent-executed"],"Desenha o trabalho, desenvolve capacidades e sustenta confiança e mudança cultural.","BCG CHRO · 2026","O CHRO emerge como arquiteto de uma força de trabalho híbrida que integra pessoas e agentes.",["O objetivo inicial é produtividade, experiência, liderança ou skills?","Redesenhar cargos ou começar decompondo tarefas?","Que trabalho um agente pode executar sem aprovação individual?","Qual risco humano exige mais atenção: confiança, capacitação, accountability ou cultura?"],"Quem é responsável pelo desenho do trabalho quando agentes passam a integrar a força de trabalho?","flowchart TD\n T[Trabalho] --> D[Decompor em tarefas]\n D --> H[Human-led]\n D --> A[AI-assisted]\n D --> G[Agent-executed]\n H --> X[Human gates]\n A --> X\n G --> X\n X --> C[Skills, cultura e governança]"),
P("jose-moreira","José Moreira","Santander","Serviços financeiros","JM","#d93838","Agentic banking","O Santander está entre os bancos com casos agentic publicados em 2026. Qual parte desse mundo é a sua?","O cenário parte do contexto do Santander e explora conexões entre clientes, pagamentos, risco, operações e tecnologia.",["Clientes & wealth","Risco & compliance","Operações & pagamentos"],"Define o território, valida ações reguladas e assume exceções de maior risco.","Santander · 2026","O banco publicou pilotos de pagamentos agentic e expansão do uso de IA em tecnologia, finanças, crime financeiro e atividade comercial.",["Qual seu território: clientes, pagamentos, risco, operações, tecnologia ou people?","O cenário é interno ou customer-facing?","O agente recomenda ou executa?","Qual ação regulada sempre deve acionar aprovação?"],"O que muda quando um cliente pode delegar uma transação a software?","flowchart TD\n I[Cliente ou colaborador] --> O[Orquestrador bancário]\n O --> C[Clientes]\n O --> R[Risco e compliance]\n O --> P[Pagamentos]\n C --> G[Consentimento e policy]\n R --> G\n P --> G\n G --> H{Aprovação humana}")
];

const caseSources:Record<string,{label:string;url:string;note?:string}[]>={
  "tom-leite":[
    {label:"Portal do Franchising / ABF — IA no Franchising",url:"https://www.portaldofranchising.com.br/noticias/inteligencia-artificial-franchising-abf-expo-2026/"},
    {label:"Business Insider — Saltz e procurement agentic",url:"https://www.businessinsider.com/agentic-ai-platform-saltz-modernizes-restaurant-food-procurement-2026-4"}
  ],
  "luiz-marcelo":[{label:"Portal do Franchising / ABF — case Grupo Trigo",url:"https://www.portaldofranchising.com.br/noticias/inteligencia-artificial-franchising-abf-expo-2026/"}],
  "jose-henrique":[{label:"Reuters — Goldman Sachs + Anthropic",url:"https://www.reuters.com/business/finance/goldman-sachs-teams-up-with-anthropic-automate-banking-tasks-with-ai-agents-cnbc-2026-02-06/"}],
  "joao-pinho":[{label:"BCG — Rebuilding Asset Management for an AI-First World",url:"https://www.bcg.com/ja-jp/publications/2026/rebuilding-asset-management-for-an-ai-first-world",note:"Referência setorial; não representa implementação da Kapitalo."}],
  "flavio-clemente":[{label:"BCG — Rebuilding Asset Management for an AI-First World",url:"https://www.bcg.com/ja-jp/publications/2026/rebuilding-asset-management-for-an-ai-first-world",note:"Referência setorial transposta para family office; não representa implementação da Heuris."}],
  "nadja-brandao":[
    {label:"Freshfields — AI Legal Workflows com Anthropic",url:"https://www.freshfields.com/en/our-thinking/news/news-search/2026/04/freshfields-and-anthropic-team-up-to-co-build-ai-legal-workflows-deploying-claude-across-the-firm-globally"},
    {label:"Financial Times — Anthropic e Freshfields",url:"https://www.ft.com/content/99c6303e-f8d0-441e-b869-6d9496874b64"}
  ],
  "mauricio-magalhaes":[
    {label:"Axios — Gradial e agentic marketing",url:"https://www.axios.com/2026/06/18/gradial-ai-agents-marketing"},
    {label:"Gradial — case T-Mobile",url:"https://www.gradial.com/customers/t-mobile"}
  ],
  "patricia-coimbra":[{label:"BCG — Reinvention of the CHRO in an AI-Driven Enterprise",url:"https://www.bcg.com/publications/2026/reinvention-of-the-chro-in-an-ai-driven-enterprise",note:"Tese e modelo operacional; não representa implementação da Porto."}],
  "jose-moreira":[{label:"Santander — pagamentos com agentes de IA na América Latina",url:"https://www.santander.com/en/press-room/press-releases/2026/03/santander-and-visa-deliver-latin-americas-first-end-to-end-payments-powered-by-ai-agents"}]
};

const mapExplanations:Record<string,string>={
  "tom-leite":"O mapa parte de um objetivo da presidência e mostra como dados, supply e suporte à franquia poderiam trabalhar de forma coordenada. A recomendação chega à operação, mas a decisão permanece humana; o resultado de cada loja alimenta o próximo ciclo.",
  "luiz-marcelo":"O mapa permite discutir uma camada comum para encaminhar demandas aos agentes certos, preservar contexto e aplicar regras de identidade, custo e segurança. Ações mais sensíveis só avançam depois de uma validação humana.",
  "jose-henrique":"O mapa mostra como diferentes frentes poderiam preparar, antes de cada conversa, uma visão única do cliente. Pesquisa, portfólio, conformidade e pendências contribuem para o mesmo briefing; você interpreta e decide o que será levado ao cliente.",
  "joao-pinho":"O mapa preserva análises independentes de macro, empresas e risco. Em vez de apagar divergências, a coordenação torna o dissenso visível, consolida a visão de portfólio e mantém a decisão final com você.",
  "flavio-clemente":"O mapa reúne patrimônio, risco, governança e impacto em um caderno de decisão comum. Ele permite comparar evidências, conflitos e cenários sem retirar da família e do time de investimentos a decisão final.",
  "nadja-brandao":"O mapa coloca governança atravessando jurídico, ESG e finanças. A hipótese permite explorar quem acessa cada informação, quais regras orientam a atuação, onde uma exceção deve parar e quem aprova a continuidade.",
  "luis-chicani":"O mapa acompanha a jornada entre colaborador, RH e benefício. Elegibilidade, rede e suporte compartilham o contexto necessário, enquanto situações sensíveis ou de cuidado continuam encaminhadas a especialistas humanos.",
  "mauricio-magalhaes":"O mapa transforma sinais de consumidor, marca e mercado em leituras concorrentes e cenários. A estratégia e a criação continuam humanas; a execução coordenada produz novos sinais para revisar o enquadramento inicial.",
  "patricia-coimbra":"O mapa parte dos objetivos do negócio e permite redesenhar tarefas entre pessoas e agentes. Gente e Cultura acompanha capacidades, impactos e regras de trabalho; líderes e equipes validam as mudanças antes de ampliar a autonomia.",
  "jose-moreira":"O mapa acompanha uma solicitação bancária entre atendimento, análise, conformidade e operação. Cada etapa recebe apenas o contexto necessário, decisões sensíveis são escaladas e o histórico permite entender por que a ação avançou ou parou."
};

const caseContexts:Record<string,string>={
  "tom-leite":"Saltz é uma referência externa de coordenação de compras: agentes reúnem e comparam informações fragmentadas de fornecedores. A conexão com sua hipótese está na coordenação entre dados, supply e operação — não em uma implementação atribuída ao Grupo Trigo.",
  "luiz-marcelo":"Microsoft, Google e AWS aparecem como referências externas para comparar padrões de coordenação, estado, governança e aprovação. Servem para tensionar escolhas de arquitetura; não descrevem a arquitetura atual do Grupo Trigo.",
  "jose-henrique":"Goldman Sachs e o estudo da BCG são referências setoriais externas sobre preparação, onboarding, pesquisa e portfólio. A relação com sua hipótese é funcional, sem atribuir ao BTG ou a você um projeto específico.",
  "joao-pinho":"O estudo da BCG é uma referência setorial externa para discutir pesquisa paralela, portfólio e operações. Os números são estimativas do relatório e não resultados da Kapitalo.",
  "flavio-clemente":"As referências combinam a pesquisa brasileira de family offices, da qual você participou no comitê consultivo, com uma visão setorial externa da BCG. Elas sustentam a discussão sobre curadoria, governança, patrimônio e legado; não descrevem uma solução implementada pela Heuris.",
  "nadja-brandao":"Freshfields–Anthropic e a arquitetura da AWS são referências externas para discutir supervisão, aprovação e trilha de auditoria. A conexão está no problema de governança, não em uma iniciativa atribuída a você.",
  "luis-chicani":"As referências de arquitetura são externas e ajudam a discutir separação de dados, limites de autonomia e encaminhamento humano em jornadas de benefícios. Não representam uma implementação da BenCorp ou do ClubSaúde.",
  "mauricio-magalhaes":"T-Mobile–Gradial e Adobe são referências externas de coordenação em marketing. A conexão com sua hipótese está no fluxo entre sinais, cenários e execução; os resultados citados pertencem aos casos publicados, não à Mundo Real.",
  "patricia-coimbra":"A BCG é uma referência externa sobre o redesenho da força de trabalho híbrida. Ela oferece uma lente para o exercício, mas não representa uma implementação ou posição oficial da Porto.",
  "jose-moreira":"O case Santander–Visa é uma referência pública da própria organização sobre pagamentos com agentes na América Latina. Ele contextualiza a hipótese, mas não permite atribuir a iniciativa à sua função individual."
};

const sectionProvocations:Record<string,string>={
  "tom-leite":"E se o Grupo Trigo tivesse um sistema de gestão capaz de coordenar especialistas digitais da mesma maneira que a holding coordena marcas, fábrica, franqueados e operações?",
  "luiz-marcelo":"Um control plane é uma camada central que encaminha demandas, compartilha contexto e aplica regras aos diferentes agentes. Como essa camada poderia conectar dados, suporte, franquias, CRM, supply e operação sem retirar a autonomia de cada área?",
  "jose-henrique":"E se, antes de cada conversa com um cliente, uma coordenação digital reunisse pesquisa de mercado, análise de portfólio, documentação, conformidade e informações de relacionamento em uma visão única — mantendo sua interpretação e sua decisão no centro?",
  "joao-pinho":"E se especialistas digitais de macroeconomia, empresas e risco trabalhassem em paralelo, preservando análises divergentes, enquanto uma camada de coordenação reunisse as exposições para apoiar sua decisão de portfólio?",
  "flavio-clemente":"Que decisões de patrimônio ganham com mais informação coordenada — e quais continuam dependendo do contexto familiar, do mandato e do julgamento de longo prazo?",
  "nadja-brandao":"Quando dois agentes chegam a recomendações incompatíveis — ambas amparadas por regras válidas — como a organização decide qual pode avançar e preserva uma responsabilidade que o conselho consiga reconstruir depois?",
  "luis-chicani":"Em uma jornada de benefícios, que informações precisam acompanhar o colaborador entre RH, operadora e atendimento — e quais devem permanecer separadas para proteger privacidade e decisões sensíveis?",
  "mauricio-magalhaes":"Se a IA torna mais barato produzir muitas alternativas, onde passa a estar a vantagem humana: na criação, na reformulação do problema ou na escolha da direção?",
  "patricia-coimbra":"O que acontece com cargos, liderança e cultura quando parte do trabalho deixa de estar contida nas pessoas e passa a circular entre equipes e agentes de IA?",
  "jose-moreira":"Em um fluxo bancário genérico — solicitação, análise, verificação de regras, aprovação, execução e confirmação — quais etapas poderiam ser coordenadas por agentes e quais deveriam permanecer sob decisão humana?"
};

const genericBankFlow="flowchart TD\n A[Solicitação do cliente] --> I[Identificar intenção e consentimento]\n I --> D[Analisar dados e documentos]\n D --> R[Verificar regras e risco]\n R --> H{Decisão humana necessária?}\n H -->|Sim| V[Aprovação humana]\n H -->|Não| E[Execução dentro dos limites]\n V --> E\n E --> C[Confirmação e registro]\n C --> F[Retorno ao cliente]";

function SectionTitle({number,children,inverse=false}:{number:string;children:string;inverse?:boolean}){return <div className={`sectionTitleUnified${inverse?" inverse":""}`}><span>{number}</span><b>{children}</b></div>}

function Mermaid({chart,explanation}:{chart:string;explanation:string}){const[svg,setSvg]=useState("");useEffect(()=>{let active=true;import("mermaid").then(async({default:m})=>{m.initialize({startOnLoad:false,theme:"base",securityLevel:"loose",fontFamily:"Arial, sans-serif",themeVariables:{primaryColor:"#f5f1e8",primaryTextColor:"#17231d",primaryBorderColor:"#b6b4a7",lineColor:"#647269",secondaryColor:"#e4efe8",tertiaryColor:"#fffdf7",fontSize:"14px"},flowchart:{curve:"basis",padding:12,nodeSpacing:26,rankSpacing:34}});const r=await m.render(`chart-${Math.random().toString(36).slice(2)}`,chart);if(active)setSvg(r.svg)});return()=>{active=false}},[chart]);return <><SectionTitle number="02" inverse>MAPA DA HIPÓTESE</SectionTitle><aside className="mapReading"><b>COMO LER ESTE MAPA</b><p>{explanation}</p></aside><div className="mermaid" aria-label="Mapa visual da hipótese" dangerouslySetInnerHTML={{__html:svg}}/></>}

const researchAsidePrefixes=["O caso de Saltz","É aí que entram as plataformas","A referência setorial de 2026","Esta hipótese não atribui","Isso se aproxima bastante da visão do relatório","A personalização ganha força porque a própria pesquisa","O caso Freshfields","Aqui a oportunidade pedagógica","O caso T-Mobile","Isso coincide diretamente com o argumento da BCG","A empresa anunciou em março de 2026","A partir daí o produto gera uma rota própria","A tela poderia terminar","Isso, curiosamente","Sua experiência pode começar","Um cenário para você explorar:","Uma possibilidade para explorar é este mapa:","Um mapa possível","Uma possibilidade de cenário:","A hipótese propõe explorar","Um cenário possível é uma"];

function FullProfile({profile}:{profile:Profile}){
  let text=profileContent[profile.slug].replace(/cite[^]+/g,"");
  const first=text.indexOf("\n\n");
  const opening=profile.slug==="tom-leite"?"Na presidência do Grupo Trigo e da ABF, você pode explorar a coordenação entre marcas, fábrica, franqueados e operações.":profile.slug==="luiz-marcelo"?"No contexto das iniciativas de IA do Grupo Trigo, você pode explorar o desenho da arquitetura corporativa.":profile.slug==="jose-henrique"?"No contexto de Private Banking, você pode explorar uma tradução relacional da orquestração:":profile.slug==="joao-pinho"?"No contexto da Kapitalo, você pode explorar especialistas que preservam autonomia de análise enquanto risco, capital e objetivos são consolidados.":profile.slug==="flavio-clemente"?"No contexto da Heuris e de family office, você pode explorar curadoria, personalização e governança em torno de patrimônio, propósito, sucessão e legado.":profile.slug==="nadja-brandao"?"No seu contexto de board, jurídico, ESG, family office e governança, você pode explorar a orquestração pela perspectiva da governança.":profile.slug==="luis-chicani"?"No contexto da BenCorp e do ClubSaúde, você pode explorar a jornada de benefícios e a gestão do risco de saúde corporativa.":profile.slug==="mauricio-magalhaes"?"Na Mundo Real, você pode explorar a orquestração a partir da metodologia “Reframing the Problem”.":profile.slug==="patricia-coimbra"?"No contexto de Gente e Cultura do Grupo Porto, você pode explorar work design e o desenho da força de trabalho híbrida.":"No contexto do Santander, você pode explorar como agentes podem conectar jornadas entre clientes, pagamentos, risco, operações e tecnologia.";
  text=opening+(first>=0?text.slice(first):"");
  text=text.replace(/As quatro perguntas que eu faria a Tom seriam:|Eu perguntaria a Luiz:|As quatro perguntas dela deveriam ser:|Perguntas adequadas:|As perguntas:|Perguntas:/g,"Quatro perguntas para você:");
  text=text.split("\n\n").filter(p=>!p.startsWith(">")&&!p.startsWith("Quatro perguntas")&&!p.startsWith("Perguntas para orientar")&&!p.startsWith("Sua primeira pergunta")&&!p.startsWith("Outras três perguntas")&&!p.startsWith("Eu perguntaria")&&!p.startsWith("**“Qual é seu território principal?")&&!p.startsWith("`Clientes/Wealth`")&&!researchAsidePrefixes.some(prefix=>p.startsWith(prefix))).join("\n\n");
  const cut=text.indexOf("\n\n");text=text.slice(0,cut)+`\n\n> **“${sectionProvocations[profile.slug]}”**`+text.slice(cut);
  return <div className="fullProfile"><ReactMarkdown components={{code({className,children,...props}){if(className?.includes("language-text"))return <Mermaid chart={profile.slug==="jose-moreira"?genericBankFlow:profile.mermaid} explanation={mapExplanations[profile.slug]}/>;return <code className={className} {...props}>{children}</code>}}}>{text}</ReactMarkdown></div>
}

export default function Home(){const[selected,setSelected]=useState<Profile|null>(null);const filtered=profiles;useEffect(()=>{document.body.style.overflow=selected?"hidden":"";return()=>{document.body.style.overflow=""}},[selected]);return <main>
<header className="topbar"><a className="brand" href="#top"><img src="/tech-hall-logo-white.png" alt="tech hall"/></a></header>
<section className="pageIntro"><span>Orquestração de IA · turma 2026</span><h1>Diagnósticos individuais</h1></section>
<section className="directory" id="top"><div className="sectionHead"><span>Selecione seu nome</span></div><div className="grid">{filtered.map((p,i)=><button className="profileCard" key={p.slug} onClick={()=>setSelected(p)} style={{"--accent":p.color} as React.CSSProperties}><div className="cardTop"><span className="index">{String(i+1).padStart(2,"0")}</span><span className="avatar">{p.initials}</span><span className="arrow">→</span></div><div><h2>{p.name}</h2><p>{p.company}</p></div><span className="lens"><b>Hipótese de cenário</b>{p.lens}</span></button>)}</div></section>
<footer><span>Orquestração de IA · 2026</span><p>Diagnósticos personalizados para a turma</p></footer>
{selected&&<div className="overlay" role="dialog" aria-modal="true"><article className="diagnosis" style={{"--accent":selected.color} as React.CSSProperties}><div className="diagNav"><button onClick={()=>setSelected(null)}>← Voltar aos participantes</button><span>Hipótese de cenário</span></div><div className="diagHero compact"><div className="personLine"><span className="avatar large">{selected.initials}</span><div><span>{selected.company}</span><h2>{selected.name}</h2><p>{selected.role}</p></div></div><div className="hypothesisFrame"><b>INTENÇÃO DO EXERCÍCIO</b><p>Este exercício apresenta uma possibilidade de orquestração de IA relacionada ao seu contexto. A intenção é oferecer um ponto de partida para você refletir sobre o tema, perceber o que faz sentido para a sua realidade e identificar questões que merecem ser exploradas.</p></div></div><section className="profileBody"><SectionTitle number="01">HIPÓTESE PARA VOCÊ EXPLORAR</SectionTitle><FullProfile profile={selected}/></section><section className="diagSection restoredQuestions"><SectionTitle number="03">PERGUNTAS PARA VOCÊ</SectionTitle><div className="questions">{selected.questions.map((q,i)=><div key={q}><span>{i+1}</span><p>{q}</p></div>)}</div></section><section className="evidence sourceOnly"><SectionTitle number="04">REFERÊNCIAS E FONTES</SectionTitle><p className="caseContext">{caseContexts[selected.slug]}</p><div className="sourceList">{caseSources[selected.slug]?.map(source=><div key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label} <b>↗</b></a>{source.note&&<small>{source.note}</small>}</div>)||<small>Referência arquitetural indicada no documento; link específico não fornecido.</small>}</div></section><div className="diagEnd"><button onClick={()=>setSelected(null)}>Ver participantes <span>→</span></button><span>Fim da hipótese · {selected.name}</span></div></article></div>}
</main>}
